apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../crd
commonAnnotations:
  helm.sh/resource-policy: keep
labels:
- pairs:
    app.kubernetes.io/name: skupper-crds
  includeSelectors: false
