{{- if and .Values.rbac.create -}}
{{ $clusterScoped := eq (include "skupper.clusterScoped" .) "true" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ if $clusterScoped -}} ClusterRoleBinding {{- else -}} RoleBinding {{- end }}
metadata:
  name: {{ include "skupper.fullname" . }}
  labels:
    {{- include "skupper.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ if $clusterScoped -}} ClusterRole {{- else -}} Role {{- end }}
  name: {{ include "skupper.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "skupper.serviceAccountName" . }}
  {{- if $clusterScoped }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
{{- end }}
